name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Publish artifacts
      run: dotnet publish --configuration Release --output ./output

    - name: Create release directory
      run: mkdir -p release  # Create release directory if it doesn't exist

    - name: List Contents of Release Directory
      run: ls -l ./release  # Verify contents of the release directory

    - name: Archive release directory
      uses: actions/upload-artifact@v3
      with:
        name: release
        path: release

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBACCESSTOKEN }}
      with:
        tag_name: v1.0.0
        release_name: Release v0.1.0
        draft: false
        prerelease: false

    # Upload release assets as needed...
