name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Publish artifacts
      run: dotnet publish --configuration Release --output ./output

    - name: Create release directory
      run: mkdir -p release

    - name: Copy build output to release directory
      run: xcopy /E /I /Y .\output\* release\

    - name: Archive release directory
      uses: actions/upload-artifact@v3
      with:
        name: release
        path: release

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBACCESSTOKEN }}
      with:
        tag_name: v1.0.0
        release_name: Release v0.1.0
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBACCESSTOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release
        asset_name: release.zip
        asset_content_type: application/zip
